In [2]:
import numpy as np

In [3]:
print(np.__version__)

arr = np.array([1, 2, 3])

2.0.2


In [9]:
# dimensions and shape of an array
arr.ndim

2

In [8]:
a = np.array([[]])
a.ndim
a.shape

(1, 0)

In [13]:
b = np.arange(0,10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
c = np.arange(1,10,2) #start, stop, step
c

array([1, 3, 5, 7, 9])

In [22]:
arr  = np.linspace(0,1,5) #start, stop, number of elements
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
arr = np.logspace(1,3,3) #start, stop, number of elements
arr

array([  10.,  100., 1000.])

In [10]:
arr = np.zeros((2,3)) #shape of the array
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr = np.ones((3,4), int) # array full of ones
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
arr = np.full(10,2) #shape of the array, value to fill
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
arr = np.full([2,4], 7) #shape of the array, value to fill [row, column], default is float
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
arr = np.empty([2,3]) #shape of the array, uninitialized values
arr

array([[3.69637888e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [10]:
arr = np.random.rand(10)  #random number between 0 and 1
arr

array([0.24490581, 0.09123093, 0.77569761, 0.79424538, 0.44606528,
       0.52316934, 0.46758323, 0.0519347 , 0.21913852, 0.35739486])

In [11]:
arr = np.random.rand(2,3) #shape of the array, random values between 0 and 1
arr

array([[0.50825373, 0.90682731, 0.89504989],
       [0.36414126, 0.23390949, 0.41936345]])

In [12]:
arr = np.random.randn(10) #random number from standard normal distribution
arr

array([-0.73571677,  1.74907861,  0.63967875, -0.59253772,  0.42984088,
       -2.28045754,  2.65457917, -0.40298661, -0.72136863,  0.21555366])

In [13]:
arr = np.random.randn(2,3) #random number from standard normal distribution
arr

array([[-2.83068546,  0.09656918,  0.99893125],
       [-0.02148047,  1.13655706, -0.03256461]])

In [31]:
arr = np.random.randint(1,100, size=(2,3)) #start, stop, number of elements
arr

array([[96, 99, 36],
       [78, 81, 58]])